---
- name: rebuild-hosts-file
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1\s'
    line: "127.0.1.1\t{{ desired_hostname | default(ansible_hostname) }}"
    state: present
