---
- name: daemon-reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: restart-activate-wled-agent
  ansible.builtin.systemd:
    name: activate-wled-agent
    state: restarted
  when: activate_agent_service_enabled
