---
- name: restart-sshd
  ansible.builtin.systemd:
    name: ssh
    state: restarted

- name: restart-fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted

- name: reload-apt-timer
  ansible.builtin.systemd:
    name: apt-daily-upgrade.timer
    daemon_reload: yes
    state: restarted
