inventory_vars_loaded: true
canary_sites:
  - warehouse
activate_agent_ref: 4e9b9db9dbd2bdbc07dfe625342d88a29830cc98
cloudflared_version: 2026.7.3
auto_apply_security_patches: true
maintenance_window_start_hour: 3
maintenance_window_end_hour: 5
ansible_pull_oncalendar: '*-*-* 02:00:00'
